import type { Metadata } from "next";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import './globals.css';
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="max-h-screen">
          {/* <Navbar/> */}
          {children} {/* <-- Add children here to render the page content */}
          <Toaster/>
        </body>
      </AuthProvider>
    </html>
  );
}
